version: '3.7'

services:
    kezia-nginx:
        image: nginx:alpine
        container_name: kezia-nginx
        ports:
            - "80:80"
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        networks:
            - kezia

    kezia-php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: kezia-php
        restart: always
        volumes:
            - .:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - kezia

    kezia-postgres:
        image: postgres:15-alpine
        container_name: kezia-postgres
        restart: always
        environment:
            POSTGRES_DB: 'kezia_db'
            POSTGRES_USER: 'kezia'
            POSTGRES_PASSWORD: 'secret'
        ports:
            - '5432:5432'
        volumes:
            - './pgdata:/var/lib/postgresql/data'
        networks:
            - kezia

networks:
    kezia:
        driver: bridge
